tags:
  - name: Course Information
    description: Real time course info
    externalDocs:
      description: Credits to
      url: 'https://github.com/qstevens'
  - name: Course Averages
    description: Historical class averages
    externalDocs:
      description: Credits to
      url: 'https://donneyfan.com/'
paths:
  /course-info/overview/{session}/{subject}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/overview/{session}/{subject}/{course}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/overview/{session}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"

  /course-info/details/{session}/{subject}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/details/{session}/{subject}/{course}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/details/{session}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2019W"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"

  # Retrieve Grade Distributions
  /coursesavg/grades/{campus}/{yearsession}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
#              type: "string"
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  # Filters
  /coursesavg/sections/{campus}/{yearsession}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/courses/{campus}/{yearsession}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/courses/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/subjects/{campus}/{yearsession}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
          description: "Academic year. Example: 2018S"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/subjects/{campus}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/yearsessions/{campus}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  # Course Profile Data
  /coursesavg/course-statistics/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/distributions/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/distributions/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/teaching-team/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/teaching-team/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
          schema:
            type: array
            items:
              default: UBCV
              enum:
                - UBCV
                - UBCO
        - name: "subject"
          in: "path"
          required: true
          type: "string"
          description: "Course code. Example: CPSC"
        - name: "course"
          in: "path"
          required: true
          type: "string"
          description: "Course number"
      responses:
        "200":
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
