#paths:
#  /api/v1/clusters/:
#    get:
#      operationId: ListClusters
#      summary: List available clusters
#      responses:
#        200:
#          description: OK
#          schema:
#            type: array
#            items:
#              $ref: '#/definitions/Cluster'
#      security:
#        - keystone: []
#    post:
#      operationId: CreateCluster
#      summary: Create a cluster
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Cluster'
#      parameters:
#        - name: body
#          in: body
#          required: true
#          schema:
#            $ref: '#/definitions/Cluster'
#      security:
#        - keystone: []
#
#definitions:
#  Cluster:
#    type: object
#    properties:
#      name:
#        description: name of the cluster
#        type: string

#---
#swagger: "2.0"
#info:
#  version: "2021-03-14T18:26:06Z"
#  title: "UBCCourses"
#host: "o1ox6y8yql.execute-api.us-east-2.amazonaws.com"
#basePath: "/test"
#schemes:
#  - "https"
tags:
  - name: Course Information
    description: Real time course info
    externalDocs:
      description: Credits to
      url: 'https://github.com/qstevens'
  - name: Course Averages
    description: Historical class averages
    externalDocs:
      description: Credits to
      url: 'https://donneyfan.com/'
paths:
  /course-info/{details-level}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "details-level"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/{details-level}/{session}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "details-level"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/{details-level}/{session}/{subject}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "details-level"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/{details-level}/{session}/{subject}/{course}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "details-level"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
        - name: "session"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/{details-level}/{session}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "details-level"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
        - name: "section"
          in: "path"
          required: true
          type: "string"
        - name: "session"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/{functionality}/{p1}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "p1"
          in: "path"
          required: true
          type: "string"
        - name: "functionality"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/{functionality}/{p1}/{p2}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "p2"
          in: "path"
          required: true
          type: "string"
        - name: "p1"
          in: "path"
          required: true
          type: "string"
        - name: "functionality"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/{functionality}/{p1}/{p2}/{p3}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "p2"
          in: "path"
          required: true
          type: "string"
        - name: "p1"
          in: "path"
          required: true
          type: "string"
        - name: "functionality"
          in: "path"
          required: true
          type: "string"
        - name: "p3"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/{functionality}/{p1}/{p2}/{p3}/{p4}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "p2"
          in: "path"
          required: true
          type: "string"
        - name: "p1"
          in: "path"
          required: true
          type: "string"
        - name: "functionality"
          in: "path"
          required: true
          type: "string"
        - name: "p4"
          in: "path"
          required: true
          type: "string"
        - name: "p3"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/{functionality}/{p1}/{p2}/{p3}/{p4}/{p5}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "p2"
          in: "path"
          required: true
          type: "string"
        - name: "p1"
          in: "path"
          required: true
          type: "string"
        - name: "p5"
          in: "path"
          required: true
          type: "string"
        - name: "functionality"
          in: "path"
          required: true
          type: "string"
        - name: "p4"
          in: "path"
          required: true
          type: "string"
        - name: "p3"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
