#paths:
#  /api/v1/clusters/:
#    get:
#      operationId: ListClusters
#      summary: List available clusters
#      responses:
#        200:
#          description: OK
#          schema:
#            type: array
#            items:
#              $ref: '#/definitions/Cluster'
#      security:
#        - keystone: []
#    post:
#      operationId: CreateCluster
#      summary: Create a cluster
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Cluster'
#      parameters:
#        - name: body
#          in: body
#          required: true
#          schema:
#            $ref: '#/definitions/Cluster'
#      security:
#        - keystone: []
#
#definitions:
#  Cluster:
#    type: object
#    properties:
#      name:
#        description: name of the cluster
#        type: string

#---
#swagger: "2.0"
#info:
#  version: "2021-03-14T18:26:06Z"
#  title: "UBCCourses"
#host: "o1ox6y8yql.execute-api.us-east-2.amazonaws.com"
#basePath: "/test"
#schemes:
#  - "https"
tags:
  - name: Course Information
    description: Real time course info
    externalDocs:
      description: Credits to
      url: 'https://github.com/qstevens'
  - name: Course Averages
    description: Historical class averages
    externalDocs:
      description: Credits to
      url: 'https://donneyfan.com/'
paths:
  /course-info/overview/{session}/{subject}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/overview/{session}/{subject}/{course}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/overview/{session}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"

  /course-info/details/{session}/{subject}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/details/{session}/{subject}/{course}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /course-info/details/{session}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Information
      produces:
        - "application/json"
      parameters:
        - name: "session"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"

  # Retrieve Grade Distributions
  /coursesavg/grades/{campus}/{yearsession}/{subject}/{course}/{section}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
        - name: "section"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/grades/{campus}/{yearsession}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  # Filters
  /coursesavg/sections/{campus}/{yearsession}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/courses/{campus}/{yearsession}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/courses/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/subjects/{campus}/{yearsession}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "yearsession"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/subjects/{campus}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/yearsessions/{campus}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  # Course Profile Data
  /coursesavg/course-statistics/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/distributions/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/distributions/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/teaching-team/{campus}/{subject}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /coursesavg/course-statistics/teaching-team/{campus}/{subject}/{course}:
    get:
      tags:
        - Course Averages
      produces:
        - "application/json"
      parameters:
        - name: "campus"
          in: "path"
          required: true
          type: "string"
        - name: "subject"
          in: "path"
          required: true
          type: "string"
        - name: "course"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
